Rearranged the repo layout yet again

diff --git a/scripts/zarchinstall b/scripts/zarchinstall
--- a/scripts/zarchinstall
+++ b/scripts/zarchinstall
@@ -22,11 +22,11 @@ while [[ "$#" -gt 0 ]]; do
     shift
 done
 
-### Prompt the user for basic safety
+### Prompt the user for basic safety or fail anyways if this is my installation
 read -rp $'\e[31mThis script will wipe everything and reformat. Type "IK" to continue: \e[0m' confirm
-if [[ "$confirm" != "IK" ]]; then
-  echo -e "\e[31mAborting.\e[0m"
-  exit 1
+if [[ "$confirm" != "IK" || "$(hostname)" == "zenixark" ]]; then
+    echo -e "\e[31mAborting (Not IK or hostname is 'zenixark').\e[0m"
+    exit 1
 fi
 
 ### Check if this is a repeat attempt and unmount affected partitions
@@ -66,7 +66,7 @@ mount -o defaults,noatime "/dev/${BOOT_PART}" /mnt/boot
 
 
 #################################################################################
-# BOOTSTRAPPING THE NEW SYSTEM
+# BOOTSTRAPPING
 #################################################################################
 
 ### Optimize pacman DL speed with an updated mirrorlist parallel downloads
@@ -84,8 +84,7 @@ pacstrap -K /mnt base base-devel btrfs-progs intel-ucode linux linux-firmware nv
 genfstab -U /mnt >> /mnt/etc/fstab
 
 ### Stage my dotfiles into the new install to be moved later
-cp -r $(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../dotfiles /mnt/dottmp
-cp $(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../services/* /mnt/etc/systemd/system
+cp -r $(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../ /mnt/.zenixark/
 
 ### Change root to the new install
 arch-chroot /mnt /bin/bash <<CHROOT
@@ -119,19 +118,8 @@ echo "user:$USER_PASS" | chpasswd
 ### Symlink .cache to tmp to wipe it on shutdown
 ln -s /tmp /home/user/.cache
 
-### Setup dotfiles that were staged earlier
-mkdir -p /home/user/.config
-mv /dottmp/.config/* /home/user/.config
-mv /dottmp/.* /home/user
-rm -rf /dottmp
-mkdir -p /home/user/.librewolf/user/chrome
-git clone https://github.com/rafaelmardojai/firefox-gnome-theme.git /tmp/fgt
-mv /tmp/fgt/theme /home/user/.librewolf/user/chrome
-mv /tmp/fgt/userChrome.css /home/user/.librewolf/user/chrome
-chown -R user:user /home/user
-
 #################################################################################
-# SETTING UP THE BOOT PROCESS
+# BOOT PROCESS
 #################################################################################
 
 ### Setup kernel options, including NVIDIA ones for gaming performance
@@ -162,7 +150,7 @@ sbctl sign -s /boot/EFI/BOOT/BOOTX64.EFI
 
 
 #################################################################################
-# SETTING UP THE USER PACKAGES
+# PACKAGES AND SERVICES
 #################################################################################
 
 ### Temporarily allow the user to use passwordless sudo for yay
@@ -177,7 +165,7 @@ cd /tmp/yay && makepkg -si --noconfirm
 yay -S --noconfirm --needed alacritty hyprland hyprpaper hyprshot iwd keepassxc librewolf-bin mullvad-vpn-cli neovim noto-fonts openrgb pipewire-jack pipewire-pulse python-nvidia-ml-py signal-desktop
 
 ### Annihilate the orphans and build files
-yay -Rcns librewolf-bin-debug mullvad-vpn-cli-debug vscodium-bin-debug python-setuptools
+yay -Rcns librewolf-bin-debug mullvad-vpn-cli-debug python-setuptools
 yay -Yc --noconfirm
 rm -rf /home/user/.cargo
 rm -rf /home/user/.config/go
@@ -190,10 +178,21 @@ pacman -D --asdeps git noto-fonts pipewire-jack
 echo "user ALL=(ALL) ALL" > /etc/sudoers.d/00_user
 chmod 440 /etc/sudoers.d/00_user
 
-
 #################################################################################
 # DOTFILES AND CONFIGURATIONS
 #################################################################################
+
+### Setup dotfiles that were staged earlier
+mv /.zenixark /home/user
+mkdir -p /home/user/.config /home/user/.librewolf/user/chrome
+ln -sf /home/user/.zenixark/configs/bash/bashrc /home/user/.bashrc
+ln -sf /home/user/.zenixark/configs/bash/bash_profile /home/user/.bash_profile
+ln -sf /home/user/.zenixark/configs/git/gitconfig /home/user/.gitconfig
+ln -sf /home/user/.zenixark/configs/hypr /home/user/.config/hypr
+ln -sf /home/user/.zenixark/configs/librewolf/user.js /home/user/.librewolf/user/user.js
+ln -sf /home/user/.zenixark/configs/librewolf/chrome /home/user/.librewolf/user/chrome
+ln -sf /home/user/.zenixark/configs/systemd/custom.service /etc/systemd/system/custom.service
+chown -R user:user /home/user
 
 ### Allow iwd to connect to the internet
 echo "[General]" > /etc/iwd/main.conf
@@ -236,19 +235,13 @@ systemctl disable nvidia-suspend
 systemctl enable fstrim.timer
 systemctl enable btrfs-scrub@-.timer
 
-### Enable essential networking services
+### Enable essential services
 systemctl enable custom
 systemctl enable iwd
 systemctl enable iptables
 systemctl enable mullvad-daemon
 systemctl enable systemd-resolved
 systemctl enable systemd-timesyncd
-
-### Configure Mullvad VPN with hardened settings
-mullvad account login $MULLVAD
-mullvad relay set location any
-mullvad auto-connect set on
-mullvad lockdown-mode set on
 
 ### Exit chroot and unmount partitions
 CHROOT
